# -*- coding: utf-8 -*-
"""BANK MARKETING ANALYTICS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1woOU6WsDI0ZgPF24Y2H6ThTaM4CmgxnL
"""

!pip install scipy sentence-transformers faiss-cpu -q

# IMPORT LIBRARIES
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import chi2_contingency
from scipy.stats import ttest_ind

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_auc_score
)

# LOAD DATA
from google.colab import files

uploaded = files.upload()

df = pd.read_csv("bank.csv")

"""# BUSINESS PROBLEM

A bank conducts marketing campaigns
to sell term deposits.

Goal:
Predict customers likely to subscribe.

Benefits:
1. Reduce marketing cost
2. Improve conversion rate
3. Increase ROI
"""

# DATA OVERVIEW


print(df.head())

print("\nShape")
print(df.shape)

print("\nInfo")
print(df.info())

print("\nSummary")
print(df.describe())

# DATA CLEANING


print("\nMissing Values")
print(df.isnull().sum())

print("\nDuplicates")
print(df.duplicated().sum())

df = df.drop_duplicates()

# TARGET ANALYSIS


print(df['deposit'].value_counts())

print(
    df['deposit'].value_counts(normalize=True)*100
)

plt.figure(figsize=(6,4))

sns.countplot(
    data=df,
    x='deposit'
)

plt.title("Deposit Subscription")

plt.show()

# AGE ANALYSIS
# ==========================================

print(df['age'].describe())

plt.figure(figsize=(8,5))

sns.histplot(
    df['age'],
    bins=30,
    kde=True
)

plt.title("Age Distribution")

plt.show()

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df,
    x='deposit',
    y='age'
)

plt.title("Age vs Deposit")

plt.show()

# AGE GROUP ANALYSIS
# ==========================================

bins = [18,25,35,45,60,100]

labels = [
    '18-25',
    '26-35',
    '36-45',
    '46-60',
    '60+'
]

df['age_group'] = pd.cut(
    df['age'],
    bins=bins,
    labels=labels
)

age_dep = pd.crosstab(
    df['age_group'],
    df['deposit'],
    normalize='index'
) * 100

print(age_dep)

# JOB ANALYSIS
# ==========================================

job_dep = pd.crosstab(
    df['job'],
    df['deposit'],
    normalize='index'
) * 100

print(job_dep)

job_dep['yes'].sort_values().plot(
    kind='barh',
    figsize=(10,6)
)

plt.title("Deposit Rate by Job")

plt.show()

# BALANCE ANALYSIS
# ==========================================

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df,
    x='deposit',
    y='balance'
)

plt.title("Balance vs Deposit")

plt.show()

# HOUSING LOAN ANALYSIS
# ==========================================

housing_table = pd.crosstab(
    df['housing'],
    df['deposit'],
    normalize='index'
) * 100

print(housing_table)

# CONTACT ANALYSIS
# ==========================================

print(
    pd.crosstab(
        df['contact'],
        df['deposit'],
        normalize='index'
    ) * 100
)

# PREVIOUS CAMPAIGN ANALYSIS
# ==========================================

print(
    pd.crosstab(
        df['poutcome'],
        df['deposit'],
        normalize='index'
    ) * 100
)

# CHI-SQUARE TEST
# ==========================================

print("\n===== CHI-SQUARE TEST =====")

table = pd.crosstab(
    df['housing'],
    df['deposit']
)

chi2, p, dof, expected = chi2_contingency(table)

print("Chi-Square:", round(chi2,2))
print("P-value:", p)

if p < 0.05:
    print("Significant relationship exists.")
else:
    print("No significant relationship.")

#T-TEST
# ==========================================

print("\n===== INDEPENDENT T-TEST =====")

yes_balance = df[
    df['deposit']=='yes'
]['balance']

no_balance = df[
    df['deposit']=='no'
]['balance']

t_stat, p_value = ttest_ind(
    yes_balance,
    no_balance,
    equal_var=False
)

print("T Statistic:", round(t_stat,2))
print("P-value:", p_value)

if p_value < 0.05:
    print("Balance differs significantly.")
else:
    print("No significant difference.")

# ENCODING
# ==========================================

df_encoded = pd.get_dummies(
    df,
    drop_first=True
)

# ==========================================
# CORRELATION
# ==========================================

corr_matrix = df_encoded.corr()

plt.figure(figsize=(20,15))

sns.heatmap(
    corr_matrix,
    cmap='coolwarm'
)

plt.title("Correlation Heatmap")

plt.show()

# FEATURES & TARGET
# ==========================================

X = df_encoded.drop(
    'deposit_yes',
    axis=1
)

y = df_encoded['deposit_yes']

# TRAIN TEST SPLIT
# ==========================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# LOGISTIC REGRESSION
# ==========================================

print("\n===== LOGISTIC REGRESSION =====")

lr = LogisticRegression(
    max_iter=1000
)

lr.fit(
    X_train,
    y_train
)

lr_pred = lr.predict(X_test)

print(
    "Accuracy:",
    accuracy_score(
        y_test,
        lr_pred
    )
)

print(
    classification_report(
        y_test,
        lr_pred
    )
)

# ROC AUC

lr_probs = lr.predict_proba(
    X_test
)[:,1]

auc = roc_auc_score(
    y_test,
    lr_probs
)

print(
    "ROC-AUC:",
    round(auc,3)
)

# CONFUSION MATRIX
# ==========================================

cm = confusion_matrix(
    y_test,
    lr_pred
)

plt.figure(figsize=(6,4))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.title(
    "Logistic Regression Confusion Matrix"
)

plt.show()

# RANDOM FOREST
# ==========================================

print("\n===== RANDOM FOREST =====")

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(
    X_train,
    y_train
)

rf_pred = rf.predict(X_test)

print(
    "Accuracy:",
    accuracy_score(
        y_test,
        rf_pred
    )
)

print(
    classification_report(
        y_test,
        rf_pred
    )
)

# FEATURE IMPORTANCE
# ==========================================

feature_importance = pd.DataFrame({

    'Feature': X.columns,

    'Importance':
    rf.feature_importances_

})

feature_importance = feature_importance.sort_values(
    by='Importance',
    ascending=False
)

print(
    feature_importance.head(15)
)

plt.figure(figsize=(10,6))

plt.barh(
    feature_importance['Feature'][:10],
    feature_importance['Importance'][:10]
)

plt.title(
    "Top 10 Important Features"
)

plt.gca().invert_yaxis()

plt.show()

# EXPORT PREDICTIONS
# ==========================================

predictions = pd.DataFrame({

    'Actual': y_test,

    'Predicted': rf_pred

})

predictions.to_csv(
    'bank_predictions.csv',
    index=False
)

feature_importance.to_csv(
    'feature_importance.csv',
    index=False
)

# ROI ANALYSIS
# ==========================================

print("\n===== ROI ANALYSIS =====")

predicted_yes = sum(rf_pred)

cost_per_call = 100

revenue_per_conversion = 1000

campaign_cost = (
    predicted_yes *
    cost_per_call
)

revenue = (
    predicted_yes *
    revenue_per_conversion
)

profit = revenue - campaign_cost

roi = (
    profit /
    campaign_cost
) * 100

print(
    "Customers Targeted:",
    predicted_yes
)

print(
    "Campaign Cost: ₹",
    campaign_cost
)

print(
    "Revenue: ₹",
    revenue
)

print(
    "Profit: ₹",
    profit
)

print(
    "ROI:",
    round(roi,2),
    "%"
)

# BUSINESS RECOMMENDATIONS
# ==========================================

print("""
BUSINESS RECOMMENDATIONS

1. Prioritize customers with longer call durations.
2. Focus on customers with previous campaign success.
3. Use predictive modeling before campaigns.
4. Target high-conversion customer segments.
5. Reduce calls to low-probability customers.
""")

# POWER BI EXPORT
# ==========================================

df.to_csv(
    'bank_dashboard.csv',
    index=False
)

print(
    "\nFiles Created:"
)

print(
    "1. bank_dashboard.csv"
)

print(
    "2. bank_predictions.csv"
)

print(
    "3. feature_importance.csv"
)

# Download Files

files.download(
    'bank_dashboard.csv'
)

files.download(
    'bank_predictions.csv'
)

files.download(
    'feature_importance.csv'
)

# ==========================================
# RAG FOR BANK MARKETING INSIGHTS
# ==========================================

!pip install sentence-transformers faiss-cpu -q

from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

# Create knowledge base from project findings

business_knowledge = [

    "Customers with longer call durations are more likely to subscribe to term deposits.",

    "Previous successful marketing campaigns significantly improve conversion rates.",

    "Random Forest was used to predict deposit subscriptions.",

    "Feature importance identifies the most influential customer attributes.",

    "Targeting high-probability customers improves campaign ROI.",

    "Customers with higher balances tend to have better subscription rates.",

    "Housing loan status influences deposit subscription behavior.",

    "Predictive analytics helps reduce unnecessary marketing costs.",

    "Logistic Regression and Random Forest were used for classification.",

    "Marketing efforts should focus on customer segments with high conversion probability."

]

# Load embedding model

model = SentenceTransformer(
    'all-MiniLM-L6-v2'
)

# Create embeddings

embeddings = model.encode(
    business_knowledge
)

# Build FAISS index

dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(
    dimension
)

index.add(
    np.array(embeddings)
)

print("Knowledge Base Created")

def ask_bank_rag(question):

    query_embedding = model.encode(
        [question]
    )

    D, I = index.search(
        np.array(query_embedding),
        k=3
    )

    print("\nQuestion:")
    print(question)

    print("\nRetrieved Insights:")

    for idx in I[0]:
        print("-", business_knowledge[idx])

ask_bank_rag(
    "What factors improve deposit subscriptions?"
)

ask_bank_rag(
    "How can the bank increase ROI?"
)

ask_bank_rag(
    "Which model was used for prediction?"
)